Split GACD for dev

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -2,9 +2,9 @@ name: Continuous Deployment
 
 on:
   push:
-    branches: [master]
+    branches: [dev]
   pull_request:
-    branches: [master]
+    branches: [dev]
 
 jobs:
   deploy:
@@ -25,12 +25,10 @@ jobs:
       - name: Store private key in a temporary file
         run: echo "${{ secrets.KEY }}" > /tmp/private_key && chmod 600 /tmp/private_key
 
-      - name: Deploy to Servers
+      - name: Deploy to Server
         run: |
-          for username in $(echo "${{ vars.USERNAMES }}" | tr ',' '\n'); do
-            echo "Deploying to $username"
-            ssh -vvv -o "IdentitiesOnly=yes" -i /tmp/private_key -p ${{ secrets.PORT }} $username@${{ secrets.HOST }} "${{ secrets.SCRIPT }}" || echo -e "\e[31mError deploying to $username\e[0m" # Red color
-          done
+          echo "Deploying to cyber32n"
+          ssh -vvv -o "IdentitiesOnly=yes" -i /tmp/private_key -p ${{ secrets.PORT }} cyber32n@${{ secrets.HOST }} "cd ecom1.cyber32.net && ./server_deploy.sh" || echo -e "\e[31mError deploying to cyber32n\e[0m" # Red color
 
       - name: Cleanup temporary files
         run: rm /tmp/private_key
